### PR TITLE
Add simple pipeline function call graph

### PR DESCRIPTION
**Pull request by FedericoCeratto**
A very basic tool to map out function calls in Jenkins.
The tool is not parsing the groovy syntax, simply matching strings.

### CODE REVIEW

**Comment by kiall** [comment]
There is also something similar built into Jenkins already - e.g. http://jenkins.caasp.suse.net/job/caasp-nightly/job/release-3.0/49/flowGraphTable/ - Could this data be used in place of string parsing?

http://jenkins.caasp.suse.net/job/caasp-nightly/job/release-3.0/49/api/xml?depth=3 - search for "FlowGraphAction"

**Comment by dannysauer** [comment]
It's been a few months; did we determine if Jenkins adequately provides this functionality yet?

**Comment by dannysauer** [comment]
Been a couple more weeks.  Is this dead?

**Comment by FedericoCeratto** [comment]
@dannysauer the script is being used as it provides a more useful output but there's no need to merge it at this time.

**Pull request closed without merging**
