### PR TITLE
Velum Bootstrap Cleanups

### PR DESCRIPTION
**Pull request by kiall**
Add some minor velum bootstrap cleanups. See commit messages for details.

### CODE REVIEW

**Comment by flavio** [comment]
@kiall can you rebase and trigger the tests again. We would like to get it merged

**Comment by MalloZup** [comment]
@flavio @ereslibre can we close this?

**Comment by MalloZup** [comment]
https://github.com/kubic-project/automation/pull/147

**Comment by MalloZup** [comment]
i close this PR in favor of the new backport thx!

**Pull request closed without merging**
