### PR TITLE
WIP: Use reactors to notify Velum of important events

### PR DESCRIPTION
**Pull request by ereslibre**
**Work in progress**, please do not review yet.

Depends on:
* https://github.com/kubic-project/velum/pull/299
* https://github.com/kubic-project/salt/pull/209
* https://github.com/kubic-project/caasp-container-manifests/pull/100

### CODE REVIEW

**Comment by ereslibre** [comment]
[Reactor callbacks](https://trello.com/c/p7L7JVQo/451-reactor-callbacks)

**Comment by MalloZup** [comment]
@ereslibre can we close this one?

**Comment by ereslibre** [comment]
Well... if I'm realistic I guess we can. Let's close this and if there's interest I can work on it.

Please, if you close it, close the dependencies too.

**Comment by MalloZup** [comment]
@ereslibre :+1:  i cannot close this at moment because some weird issues on my useraccount. feel free to close it and i will close the card in trello

**Comment by MalloZup** [comment]
closing as discussed

**Pull request closed without merging**
