### PR TITLE
[WIP] [NEVER MERGE] Temporary pipeline

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Run CI on a test 4.0 image

### CODE REVIEW

**Comment by FedericoCeratto** [comment]
(test)

**Comment by FedericoCeratto** [comment]
(test)

**Comment by stefsuse** [comment]
These kinds of changes do not belong in a PR. Please use the test scripts in gitlab that were created for this purpose. Thanks.

**Comment by FedericoCeratto** [comment]
Testing completed.

**Pull request closed without merging**
