### PR TITLE
Add more RAM to the admin node.

### PR DESCRIPTION
**Pull request by ereslibre**
4GB are insufficient to run the rspec suite. Bumping to 8GB.

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
@ereslibre @vitoravelino can you also try to run it locally with:

* https://github.com/kubic-project/caasp-container-manifests/pull/156 and
* https://github.com/kubic-project/velum/pull/464

applied and see if that behaves better? i tried it locally and during capybara bootstrap all the ruby processes were consuming ~20% of all the 4GB RAM and all the salt-master processes consumed about 40-50%

the admin was still usable and didn't show any signs of being laggy during that load

**Comment by vitoravelino** [comment]
Really? I'm gonna try it then. Thanks for the tip!

**Comment by MalloZup** [comment]
@ereslibre @MaximilianMeister  do we still need this or we can close it ? tia

**Comment by MaximilianMeister** [comment]
> do we still need this or we can close it ? tia

good question, the default for the admin is 8GB nowadays. so this makes sense. i'm only worried about running a cluster locally as i only have 16GB RAM (most people probably don't ahve more)

**Comment by MalloZup** [comment]
imho we can merge it, and for your case people should make less.

If in Prod we use 8gb, imho the local environment should have 8gb reflectiong 1:1 prod. 
For special use-cases users can diminish their ram

**Comment by MalloZup** [comment]
@ereslibre for me looks good.
@MaximilianMeister  your take if we want it or not.

If we want this, rebase the branch :tia

**Comment by MaximilianMeister** [comment]
@ereslibre can you rebase?

**Pull request closed without merging**
