### PR TITLE
enable bootstrap after deployment

### PR DESCRIPTION
**Pull request by MaximilianMeister**
Signed-off-by: Maximilian Meister <mmeister@suse.de>

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
i also like the separation, but I am not sure what you mean. the components are still separate.

this is only for local usage, no CI is affected, therefore there is no combination of any components by default. I'd really like to have this because I have to do the steps manually all the time.

**Comment by kiall** [comment]
Oh -

**Comment by kiall** [comment]
Oh - wow.. I must have hit close an comment. Sorry :)

This is the kinda thing I meant: https://github.com/kubic-project/automation/pull/47

**Comment by MaximilianMeister** [comment]
closing in favor of #47

**Comment by MaximilianMeister** [comment]
closing in favor of #47

**Pull request closed without merging**
